# Generated by Django 6.0 on 2026-02-01 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_img",
            field=models.ImageField(
                default=django.utils.timezone.now,
                upload_to="",
                verbose_name="Item Image",
            ),
            preserve_default=False,
        ),
    ]
