# Generated by Django 6.0 on 2026-02-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_item_item_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_img",
            field=models.ImageField(upload_to="media/", verbose_name="Item Image"),
        ),
    ]
